import React, { useState } from 'react';
import { Bold, Italic, Underline, List, ListOrdered, Image, Table as TableIcon, Plus, Trash2 } from 'lucide-react';
import SimpleRichTextEditor from './SimpleRichTextEditor';
import StructuredAnswerEditor from './StructuredAnswerEditor';
import { Discourse, DiscourseScores, BlueprintItem, Unit, SubUnit, AnswerMark } from '../types';

export const QuestionRow = ({ item, index, onUpdateItem, availableDiscourses, systemSettings, curriculum, section, sectionItems }: any) => {
    const [activeTab, setActiveTab] = useState<'question' | 'answer'>('question');
    const [questionMode, setQuestionMode] = useState<'content' | 'structured'>(
        (item.structuredQuestions && item.structuredQuestions.length > 0) ? 'structured' : 'content'
    );
    const [questionModeB, setQuestionModeB] = useState<'content' | 'structured'>(
        (item.structuredQuestionsB && item.structuredQuestionsB.length > 0) ? 'structured' : 'content'
    );
    const [answerMode, setAnswerMode] = useState<'content' | 'discourse' | 'ai' | 'structured'>(
        (item.structuredAnswers && item.structuredAnswers.length > 0) ? 'structured' : 'content'
    );
    const [answerModeB, setAnswerModeB] = useState<'content' | 'discourse' | 'ai' | 'structured'>(
        (item.structuredAnswersB && item.structuredAnswersB.length > 0) ? 'structured' : 'content'
    );
    const [isGenerating, setIsGenerating] = useState(false);
    const [selectedDiscourseId, setSelectedDiscourseId] = useState<string>(item.discourseId || '');
    const [selectedDiscourseIdB, setSelectedDiscourseIdB] = useState<string>(item.discourseIdB || '');

    // Helpers for Unit selection
    const selectedUnit = curriculum?.units.find((u: Unit) => u.id === item.unitId);
    const availableSubUnits = selectedUnit?.subUnits || [];

    const sectionOptionCount = section?.optionCount || 0;
    const currentSectionOptionUsage = sectionItems?.filter((si: any) => si.hasInternalChoice).length || 0;

    // Limits based on mark rules: 1 & 2 marks have no option.
    const isMarkRestricted = item.marksPerQuestion <= 2;
    // Can't enable if we hit the limit, UNLESS it's already enabled
    const isLimitReached = !item.hasInternalChoice && currentSectionOptionUsage >= sectionOptionCount;
    const canToggleOption = !isMarkRestricted && (item.hasInternalChoice || !isLimitReached);

    const formatMarks = (marks: number) => {
        const s = marks.toString();
        if (s.endsWith('.5')) {
            const whole = s.split('.')[0];
            return whole === '0' ? '½' : `${whole}½`;
        }
        return s;
    };

    const generateAIAnswer = (targetField: 'answerText' | 'answerTextB', sourceField: 'questionText' | 'questionTextB') => {
        setIsGenerating(true);
        setTimeout(() => {
            onUpdateItem(item.id, targetField, `<p>Answer generated by AI based on: "${item[sourceField] || 'question'}"</p>`);
            setIsGenerating(false);
            if (targetField === 'answerText') setAnswerMode('content');
            else setAnswerModeB('content');
        }, 1500);
    };

    const applyDiscourse = (discourseId: string, targetField: 'answerText' | 'answerTextB') => {
        const d = availableDiscourses.find((x: Discourse) => x.id === discourseId);
        if (d) {
            // Apply Cognitive Process if present in Discourse (only for main/A option or global)
            if (d.cognitiveProcess && targetField === 'answerText') {
                onUpdateItem(item.id, 'cognitiveProcess', d.cognitiveProcess);
            }

            // Save the discourse ID to the item for persistence
            // This is used by AnswerKeyView to render the standard rubric details
            if (targetField === "answerText") {
                onUpdateItem(item.id, "discourseId", discourseId);
            } else {
                onUpdateItem(item.id, "discourseIdB", discourseId);
            }
        }
    };

    return (
        <div className="border rounded-lg bg-white shadow-sm hover:shadow-md transition-shadow">
            {/* Header / Metadata Row */}
            <div className="bg-gray-50 p-2 md:p-3 border-b flex flex-col md:flex-row gap-3 md:gap-4 items-start md:items-center justify-between rounded-t-lg">
                <div className="flex items-center gap-2 md:gap-3 w-full md:w-auto justify-between md:justify-start">
                    <div className="flex items-center gap-2">
                        <span className="w-8 h-8 rounded-full bg-blue-600 text-white flex items-center justify-center font-bold text-sm shrink-0">
                            Q{index + 1}
                        </span>
                        <div className="flex flex-col md:flex-row md:items-center gap-0 md:gap-2">
                            <span className="font-bold text-gray-700 text-xs md:text-sm">
                                {formatMarks(item.marksPerQuestion)} Mark{item.marksPerQuestion > 1 ? 's' : ''}
                            </span>
                        </div>
                    </div>

                    {/* Internal Choice Toggle - Mobile Compact */}
                    <div className="flex items-center gap-2 pl-3 border-l md:border-l-0 md:pl-0">
                        <span className="hidden sm:inline english-font font-bold text-gray-500 uppercase tracking-widest text-[9px]">Internal Choice</span>
                        <button
                            onClick={() => {
                                if (canToggleOption) {
                                    const nextValue = !item.hasInternalChoice;
                                    onUpdateItem(item.id, 'hasInternalChoice', nextValue);
                                    if (nextValue) {
                                        if (!item.knowledgeLevelB) onUpdateItem(item.id, 'knowledgeLevelB', item.knowledgeLevel);
                                        if (!item.cognitiveProcessB) onUpdateItem(item.id, 'cognitiveProcessB', item.cognitiveProcess);
                                        if (!item.itemFormatB) onUpdateItem(item.id, 'itemFormatB', item.itemFormat);
                                    }
                                }
                            }}
                            disabled={!canToggleOption}
                            className={`w-9 h-4.5 md:w-10 md:h-5 rounded-full p-1 transition-all ${item.hasInternalChoice ? 'bg-blue-600' : 'bg-gray-300'} ${!canToggleOption ? 'opacity-30 cursor-not-allowed' : 'hover:scale-105'}`}
                            title={isMarkRestricted ? "No option for 1 or 2 marks" : "Enable Internal Choice"}
                        >
                            <div className={`w-2.5 h-2.5 md:w-3 md:h-3 bg-white rounded-full transition-transform ${item.hasInternalChoice ? 'translate-x-4.5 md:translate-x-5' : 'translate-x-0'}`} />
                        </button>
                    </div>
                </div>

                <div className="grid grid-cols-2 sm:grid-cols-3 lg:flex flex-wrap gap-1.5 md:gap-2 items-center w-full md:w-auto">
                    {curriculum && (
                        <>
                            <div className="flex flex-col col-span-2 sm:col-span-1">
                                <label className="text-[9px] font-bold text-gray-400 uppercase md:hidden px-1">Unit</label>
                                <select
                                    className="border-2 border-slate-100 rounded-lg px-2 py-1 text-[11px] font-bold text-gray-900 bg-white focus:border-blue-300 focus:ring-4 focus:ring-blue-50 transition-all outline-none w-full md:max-w-[150px]"
                                    value={item.unitId}
                                    onChange={(e: React.ChangeEvent<HTMLSelectElement>) => {
                                        onUpdateItem(item.id, 'unitId', e.target.value);
                                        const newUnit = curriculum.units.find((u: Unit) => u.id === e.target.value);
                                        onUpdateItem(item.id, 'subUnitId', newUnit?.subUnits[0]?.id || '');
                                    }}
                                >
                                    {curriculum.units.map((u: Unit) => <option key={u.id} value={u.id}>Unit {u.unitNumber}</option>)}
                                </select>
                            </div>

                            <div className="flex flex-col col-span-2 sm:col-span-1">
                                <label className="text-[9px] font-bold text-gray-400 uppercase md:hidden px-1">Sub-Unit</label>
                                <select
                                    className="border-2 border-slate-100 rounded-lg px-2 py-1 text-[11px] font-bold text-gray-900 bg-white focus:border-blue-300 focus:ring-4 focus:ring-blue-50 transition-all outline-none w-full md:max-w-[150px]"
                                    value={item.subUnitId}
                                    onChange={(e: React.ChangeEvent<HTMLSelectElement>) => onUpdateItem(item.id, 'subUnitId', e.target.value)}
                                    disabled={!item.unitId || availableSubUnits.length === 0}
                                >
                                    {availableSubUnits.length === 0 && <option value="">No Subunits</option>}
                                    {availableSubUnits.map((s: SubUnit) => <option key={s.id} value={s.id}>{s.name}</option>)}
                                </select>
                            </div>
                        </>
                    )}

                    <div className="flex flex-col">
                        <label className="text-[9px] font-bold text-gray-400 uppercase md:hidden px-1">Level</label>
                        <select
                            className={`border-2 border-slate-100 rounded-lg px-2 py-1 text-[11px] font-bold text-gray-900 bg-white focus:border-blue-300 focus:ring-4 focus:ring-blue-50 transition-all outline-none w-full ${item.marksPerQuestion === 1 ? 'opacity-75 bg-gray-50' : ''}`}
                            value={item.knowledgeLevel}
                            onChange={(e: React.ChangeEvent<HTMLSelectElement>) => onUpdateItem(item.id, 'knowledgeLevel', e.target.value)}
                            disabled={item.marksPerQuestion === 1}
                        >
                            {systemSettings.knowledgeLevels.map((k: any) => <option key={k.code} value={k.name}>{k.name}</option>)}
                        </select>
                    </div>

                    <div className="flex flex-col">
                        <label className="text-[9px] font-bold text-gray-400 uppercase md:hidden px-1">Process</label>
                        <select
                            className="border-2 border-slate-100 rounded-lg px-2 py-1 text-[11px] font-bold text-gray-900 bg-white focus:border-blue-300 focus:ring-4 focus:ring-blue-50 transition-all outline-none w-full"
                            value={item.cognitiveProcess}
                            onChange={(e: React.ChangeEvent<HTMLSelectElement>) => onUpdateItem(item.id, 'cognitiveProcess', e.target.value)}
                        >
                            {systemSettings.cognitiveProcesses.map((c: any) => <option key={c.code} value={c.description}>{c.name}</option>)}
                        </select>
                    </div>

                    <div className="flex flex-col">
                        <label className="text-[9px] font-bold text-gray-400 uppercase md:hidden px-1">Format</label>
                        <select
                            className="border-2 border-slate-100 rounded-lg px-2 py-1 text-[11px] font-bold text-gray-900 bg-white focus:border-blue-300 focus:ring-4 focus:ring-blue-50 transition-all outline-none w-full"
                            value={item.itemFormat}
                            onChange={(e: React.ChangeEvent<HTMLSelectElement>) => onUpdateItem(item.id, 'itemFormat', e.target.value)}
                        >
                            {systemSettings.itemFormats.map((f: any) => <option key={f.code} value={f.name}>{f.name}</option>)}
                        </select>
                    </div>

                    <div className="flex flex-col">
                        <label className="text-[9px] font-bold text-gray-400 uppercase md:hidden px-1">Time</label>
                        <div className="flex items-center gap-1 border-2 border-slate-100 rounded-lg px-2 py-1 bg-white focus-within:border-blue-300 focus-within:ring-4 focus-within:ring-blue-50 transition-all">
                            <input
                                type="number"
                                className="w-12 text-[11px] font-bold text-gray-900 outline-none bg-transparent text-center"
                                value={item.time || ''}
                                onChange={(e) => onUpdateItem(item.id, 'time', parseInt(e.target.value) || 0)}
                                placeholder="Min"
                                min="0"
                            />
                            <span className="text-[9px] font-bold text-gray-400 uppercase">Min</span>
                        </div>
                    </div>
                </div>
            </div>

            {/* Content Area */}
            <div className="p-3 md:p-4">
                {/* Tabs */}
                <div className="flex border-b mb-4">
                    <button
                        onClick={() => setActiveTab('question')}
                        className={`px-4 py-2 text-sm font-bold mr-1 rounded-t-lg transition-colors ${activeTab === 'question' ? 'bg-blue-50 text-blue-700 border-b-2 border-blue-600' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        Question
                    </button>
                    <button
                        onClick={() => setActiveTab('answer')}
                        className={`px-4 py-2 text-sm font-bold rounded-t-lg transition-colors ${activeTab === 'answer' ? 'bg-green-50 text-green-700 border-b-2 border-green-600' : 'text-gray-500 hover:text-gray-700'}`}
                    >
                        Answer
                    </button>
                </div>

                {/* Tab Content */}
                <div className="min-h-[150px]">
                    {activeTab === 'question' && (
                        <div className="animate-fade-in space-y-6">
                            {/* Option A (Default) */}
                            <div>
                                {item.hasInternalChoice && <div className="tamil-font font-bold text-red-600 mb-1">ஏதேனும் ஒன்றிற்கு விடையளிக்கவும்</div>}
                                {item.hasInternalChoice && <div className="tamil-font font-bold text-blue-600 mb-1">(அ) வினா</div>}
                                
                                {questionMode === 'content' ? (
                                    <SimpleRichTextEditor
                                        value={item.questionText}
                                        onChange={(val: string) => onUpdateItem(item.id, 'questionText', val)}
                                        placeholder="Type the question content here..."
                                        onToggleStructured={() => setQuestionMode('structured')}
                                    />
                                ) : (
                                    <div className="space-y-2">
                                        <div className="flex justify-between items-center bg-blue-50/50 p-2 rounded-t border-t border-x px-4">
                                            <span className="text-xs font-bold text-blue-600 uppercase tracking-widest">Structured Question Mode</span>
                                            <button onClick={() => setQuestionMode('content')} className="text-[10px] font-bold text-blue-700 hover:underline">Switch to Plain Text</button>
                                        </div>
                                        <StructuredAnswerEditor
                                            value={item.structuredQuestions || []}
                                            label="Question Point"
                                            placeholder="Enter question point..."
                                            onChange={(val: AnswerMark[]) => {
                                                onUpdateItem(item.id, 'structuredQuestions', val as any);
                                                const html = `<ul class="rubric-list">${val.map(v => `<li><span class="rubric-point">${v.answer}</span><strong class="rubric-mark">${v.mark}</strong></li>`).join('')}</ul>`;
                                                onUpdateItem(item.id, 'questionText', html);
                                            }}
                                        />
                                    </div>
                                )}
                            </div>

                            {item.hasInternalChoice && (
                                <div className="tamil-font font-bold text-purple-600 flex items-center gap-2">
                                    <span className="bg-purple-600 text-white px-1.5 py-0.5 rounded text-[10px]">அல்லது</span>
                                </div>
                            )}

                            {/* Option B (If Enabled) */}
                            {item.hasInternalChoice && (
                                <div className="border-t pt-1 bg-purple-50/20 p-2 md:p-4 rounded-lg border border-purple-100">
                                    <div className="flex flex-wrap justify-between items-center mb-3 gap-2">
                                        <div className="flex items-center gap-4">
                                            <div className="tamil-font font-bold text-blue-600 mb-1"> (ஆ) வினா </div>
                                            
                                            <div className="flex gap-2">
                                                <select
                                                    className="border rounded px-2 py-0.5 text-[10px] bg-white focus:ring-2 focus:ring-blue-100 outline-none"
                                                    value={item.knowledgeLevelB || item.knowledgeLevel}
                                                    onChange={(e: React.ChangeEvent<HTMLSelectElement>) => onUpdateItem(item.id, 'knowledgeLevelB', e.target.value)}
                                                >
                                                    {systemSettings.knowledgeLevels.map((k: any) => <option key={k.code} value={k.name}>{k.name}</option>)}
                                                </select>

                                                <select
                                                    className="border rounded px-2 py-0.5 text-[10px] bg-white focus:ring-2 focus:ring-blue-100 outline-none"
                                                    value={item.cognitiveProcessB || item.cognitiveProcess}
                                                    onChange={(e: React.ChangeEvent<HTMLSelectElement>) => onUpdateItem(item.id, 'cognitiveProcessB', e.target.value)}
                                                >
                                                    {systemSettings.cognitiveProcesses.map((c: any) => <option key={c.code} value={c.description}>{c.name}</option>)}
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    {questionModeB === 'content' ? (
                                        <SimpleRichTextEditor
                                            value={item.questionTextB}
                                            onChange={(val: string) => onUpdateItem(item.id, 'questionTextB', val)}
                                            placeholder="Type the (ஆ) question content..."
                                            onToggleStructured={() => setQuestionModeB('structured')}
                                        />
                                    ) : (
                                        <div className="space-y-2">
                                            <div className="flex justify-between items-center bg-purple-50/50 p-2 rounded-t border-t border-x px-4">
                                                <span className="text-xs font-bold text-purple-600 uppercase tracking-widest">Structured Question Mode (B)</span>
                                                <button onClick={() => setQuestionModeB('content')} className="text-[10px] font-bold text-purple-700 hover:underline">Switch to Plain Text</button>
                                            </div>
                                            <StructuredAnswerEditor
                                                value={item.structuredQuestionsB || []}
                                                label="Question Point"
                                                placeholder="Enter question point..."
                                                onChange={(val: AnswerMark[]) => {
                                                    onUpdateItem(item.id, 'structuredQuestionsB', val as any);
                                                    const html = `<ul class="rubric-list">${val.map(v => `<li><span class="rubric-point">${v.answer}</span><strong class="rubric-mark">${v.mark}</strong></li>`).join('')}</ul>`;
                                                    onUpdateItem(item.id, 'questionTextB', html);
                                                }}
                                            />
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    )}

                    {activeTab === 'answer' && (
                        <div className="animate-fade-in space-y-6">
                            {/* Option A Answer */}
                            <div className="space-y-4">
                                {item.hasInternalChoice && <div className="tamil-font font-bold text-blue-600">(அ) Answer Key</div>}

                                {/* Checkboxes for Modes */}
                                <div className="flex flex-wrap items-center gap-3 md:gap-5 mb-4 bg-gray-50/80 p-3 rounded-lg border border-gray-200 shadow-sm">
                                    <label className="flex items-center gap-2 cursor-pointer group">
                                        <input 
                                            type="checkbox" 
                                            className="w-4 h-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500 cursor-pointer"
                                            checked={!!item.enableWriteContent}
                                            onChange={(e) => onUpdateItem(item.id, 'enableWriteContent', e.target.checked)}
                                        />
                                        <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-blue-600 transition-colors uppercase tracking-wider">Write Content</span>
                                    </label>
                                    <label 
                                        className={`flex items-center gap-2 cursor-pointer group ${item.marksPerQuestion <= 2 ? 'opacity-50 cursor-not-allowed' : ''}`}
                                        title={item.marksPerQuestion <= 2 ? "Discourse not available for 1 or 2 mark questions" : ""}
                                    >
                                        <input 
                                            type="checkbox" 
                                            className="w-4 h-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 cursor-pointer disabled:cursor-not-allowed"
                                            checked={!!item.enableDiscourse}
                                            onChange={(e) => onUpdateItem(item.id, 'enableDiscourse', e.target.checked)}
                                            disabled={item.marksPerQuestion <= 2}
                                        />
                                        <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-indigo-600 transition-colors uppercase tracking-wider">Select Discourse</span>
                                    </label>
                                    <label className="flex items-center gap-2 cursor-pointer group">
                                        <input 
                                            type="checkbox" 
                                            className="w-4 h-4 rounded border-gray-300 text-green-600 focus:ring-green-500 cursor-pointer"
                                            checked={!!item.enableInputAnswer}
                                            onChange={(e) => onUpdateItem(item.id, 'enableInputAnswer', e.target.checked)}
                                        />
                                        <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-green-600 transition-colors uppercase tracking-wider">Input Answer</span>
                                    </label>
                                    <label className="flex items-center gap-2 cursor-pointer group">
                                        <input 
                                            type="checkbox" 
                                            className="w-4 h-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500 cursor-pointer"
                                            checked={!!item.enableFurtherInfo}
                                            onChange={(e) => onUpdateItem(item.id, 'enableFurtherInfo', e.target.checked)}
                                        />
                                        <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-purple-600 transition-colors uppercase tracking-wider">Further Information</span>
                                    </label>
                                </div>

                                {item.enableWriteContent && (
                                    <div className="space-y-3 animate-slide-up">
                                        <div className="flex justify-between items-center">
                                            <h4 className="text-[10px] font-black text-blue-600 uppercase tracking-widest pl-1">Write Content</h4>
                                            <button
                                                onClick={() => generateAIAnswer('answerText', 'questionText')}
                                                disabled={isGenerating || !item.questionText}
                                                className="bg-blue-600 text-white px-3 py-1 text-[10px] font-bold rounded shadow hover:bg-blue-700 disabled:bg-gray-400 transition flex items-center gap-1.5"
                                            >
                                                {isGenerating ? 'Generating...' : 'Generate with AI'}
                                            </button>
                                        </div>
                                        <SimpleRichTextEditor
                                            value={item.answerText}
                                            onChange={(val: string) => onUpdateItem(item.id, 'answerText', val)}
                                            placeholder="Type answer content or key points..."
                                            isAnswerTab={true}
                                        />
                                    </div>
                                )}

                                {item.enableDiscourse && (
                                    <div className="border rounded-xl p-4 bg-indigo-50/30 border-indigo-100 animate-slide-up">
                                        <h4 className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-3">Select Discourse</h4>
                                        <div className="flex gap-2">
                                            {availableDiscourses.length === 0 ? (
                                                <p className="text-red-500 text-[11px] italic">No discourses found for {item.marksPerQuestion} Marks.</p>
                                            ) : (
                                                <select
                                                    className="w-full border p-2 rounded-lg text-sm bg-white shadow-sm focus:ring-2 focus:ring-indigo-100 outline-none"
                                                    onChange={(e: React.ChangeEvent<HTMLSelectElement>) => {
                                                        const id = e.target.value;
                                                        setSelectedDiscourseId(id);
                                                        if (id) applyDiscourse(id, 'answerText');
                                                    }}
                                                    value={selectedDiscourseId}
                                                >
                                                    <option value="" disabled>-- Choose Discourse --</option>
                                                    {availableDiscourses.map((d: Discourse) => (
                                                        <option key={d.id} value={d.id}>{d.name} ({formatMarks(d.marks)} Marks)</option>
                                                    ))}
                                                </select>
                                            )}
                                        </div>

                                        {/* Discourse Preview A */}
                                        {selectedDiscourseId && (
                                            <div className="mt-4 p-5 bg-white border border-indigo-100 rounded-xl shadow-[0_4px_20px_-5px_rgba(79,70,229,0.1)] animate-fade-in relative overflow-hidden">
                                                <div className="absolute top-0 right-0 w-24 h-24 bg-indigo-50 rounded-full -mr-12 -mt-12 -z-0 opacity-50"></div>
                                                
                                                <div className="relative z-10">
                                                    <div className="flex justify-between items-start mb-3">
                                                        <div>
                                                            <h5 className="font-bold text-indigo-900 text-base">{availableDiscourses.find(d => d.id === selectedDiscourseId)?.name}</h5>
                                                            <div className="flex flex-wrap gap-2 mt-1">
                                                                <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-indigo-100 text-indigo-700 border border-indigo-200 uppercase tracking-wide">
                                                                    {availableDiscourses.find(d => d.id === selectedDiscourseId)?.cognitiveProcess || 'No CP'}
                                                                </span>
                                                                <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-green-100 text-green-700 border border-green-200 uppercase tracking-wide">
                                                                    {formatMarks(availableDiscourses.find(d => d.id === selectedDiscourseId)?.marks || 0)} Marks
                                                                </span>
                                                            </div>
                                                        </div>
                                                        <span className="text-[9px] bg-slate-100 text-slate-500 px-2 py-1 rounded-full font-black uppercase tracking-tighter">Preview Mode</span>
                                                    </div>

                                                    <div className="bg-slate-50/80 p-3 rounded-lg border border-slate-100 mb-4">
                                                        <p className="text-[11px] leading-relaxed text-slate-600 italic">
                                                            {availableDiscourses.find(d => d.id === selectedDiscourseId)?.description}
                                                        </p>
                                                    </div>

                                                    <div className="space-y-1.5">
                                                        <div className="flex items-center gap-2 mb-2">
                                                            <div className="h-[1px] flex-grow bg-indigo-100"></div>
                                                            <span className="text-[9px] font-black text-indigo-300 uppercase tracking-widest">Rubric Points</span>
                                                            <div className="h-[1px] flex-grow bg-indigo-100"></div>
                                                        </div>
                                                        <div className="grid grid-cols-1 gap-1.5">
                                                            {availableDiscourses.find(d => d.id === selectedDiscourseId)?.rubrics.map((r: any, i: number) => (
                                                                <div key={i} className="flex justify-between items-center text-[10px] bg-white p-2.5 rounded-lg border border-indigo-50 hover:border-indigo-200 hover:shadow-sm transition-all group">
                                                                    <span className="text-slate-700 font-medium">{r.point}</span>
                                                                    <span className="font-bold text-indigo-600 bg-indigo-50/50 px-2 py-1 rounded border border-indigo-100 group-hover:bg-indigo-600 group-hover:text-white transition-colors">
                                                                        {formatMarks(r.marks)}
                                                                    </span>
                                                                </div>
                                                            ))}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        )}
                                    </div>
                                )}

                                {item.enableInputAnswer && (
                                     <div className="space-y-2 animate-slide-up">
                                         <h4 className="text-[10px] font-black text-green-600 uppercase tracking-widest pl-1">Input Answer (Structured)</h4>
                                         <StructuredAnswerEditor
                                             value={item.structuredAnswers || []}
                                             onChange={(val: AnswerMark[]) => {
                                                 onUpdateItem(item.id, 'structuredAnswers', val as any);
                                             }}
                                         />
                                     </div>
                                 )}

                                {item.enableFurtherInfo && (
                                    <div className="space-y-2 animate-slide-up">
                                        <h4 className="text-[10px] font-black text-purple-600 uppercase tracking-widest pl-1">Further Information</h4>
                                        <textarea
                                            rows={2}
                                            className="w-full border-2 border-purple-50 rounded-xl px-4 py-3 text-sm focus:border-purple-300 focus:ring-4 focus:ring-purple-50 outline-none transition-all placeholder:text-gray-300"
                                            placeholder="Enter any additional field information here..."
                                            value={item.furtherInfo || ''}
                                            onChange={(e) => onUpdateItem(item.id, 'furtherInfo', e.target.value)}
                                        />
                                    </div>
                                )}
                            </div>

                            {/* Option B Answer */}
                            {item.hasInternalChoice && (
                                <div className="space-y-4 pt-6 border-t font-sans">
                                    <div className="tamil-font font-bold text-purple-600">(ஆ) Answer Key (Option B)</div>
                                    
                                    <div className="flex flex-wrap items-center gap-3 md:gap-5 mb-4 bg-gray-50/80 p-3 rounded-lg border border-gray-200">
                                        <label className="flex items-center gap-2 cursor-pointer group">
                                            <input 
                                                type="checkbox" 
                                                className="w-4 h-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500 cursor-pointer"
                                                checked={!!item.enableWriteContentB}
                                                onChange={(e) => onUpdateItem(item.id, 'enableWriteContentB', e.target.checked)}
                                            />
                                            <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-blue-600 transition-colors uppercase tracking-wider">Write Content</span>
                                        </label>
                                        <label 
                                            className={`flex items-center gap-2 cursor-pointer group ${item.marksPerQuestion <= 2 ? 'opacity-50 cursor-not-allowed' : ''}`}
                                            title={item.marksPerQuestion <= 2 ? "Discourse not available for 1 or 2 mark questions" : ""}
                                        >
                                            <input 
                                                type="checkbox" 
                                                className="w-4 h-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500 cursor-pointer disabled:cursor-not-allowed"
                                                checked={!!item.enableDiscourseB}
                                                onChange={(e) => onUpdateItem(item.id, 'enableDiscourseB', e.target.checked)}
                                                disabled={item.marksPerQuestion <= 2}
                                            />
                                            <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-indigo-600 transition-colors uppercase tracking-wider">Select Discourse</span>
                                        </label>
                                        <label className="flex items-center gap-2 cursor-pointer group">
                                            <input 
                                                type="checkbox" 
                                                className="w-4 h-4 rounded border-gray-300 text-green-600 focus:ring-green-500 cursor-pointer"
                                                checked={!!item.enableInputAnswerB}
                                                onChange={(e) => onUpdateItem(item.id, 'enableInputAnswerB', e.target.checked)}
                                            />
                                            <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-green-600 transition-colors uppercase tracking-wider">Input Answer</span>
                                        </label>
                                        <label className="flex items-center gap-2 cursor-pointer group">
                                            <input 
                                                type="checkbox" 
                                                className="w-4 h-4 rounded border-gray-300 text-purple-600 focus:ring-purple-500 cursor-pointer"
                                                checked={!!item.enableFurtherInfoB}
                                                onChange={(e) => onUpdateItem(item.id, 'enableFurtherInfoB', e.target.checked)}
                                            />
                                            <span className="text-[11px] md:text-xs font-bold text-gray-700 group-hover:text-purple-600 transition-colors uppercase tracking-wider">Further Information</span>
                                        </label>
                                    </div>

                                    {item.enableWriteContentB && (
                                        <div className="space-y-3 animate-slide-up">
                                            <div className="flex justify-between items-center">
                                                <h4 className="text-[10px] font-black text-blue-600 uppercase tracking-widest pl-1">Write Content (B)</h4>
                                                <button
                                                    onClick={() => generateAIAnswer('answerTextB', 'questionTextB')}
                                                    disabled={isGenerating || !item.questionTextB}
                                                    className="bg-blue-600 text-white px-3 py-1 text-[10px] font-bold rounded shadow hover:bg-blue-700 disabled:bg-gray-400 transition flex items-center gap-1.5"
                                                >
                                                    {isGenerating ? 'Generating...' : 'Generate with AI'}
                                                </button>
                                            </div>
                                            <SimpleRichTextEditor
                                                value={item.answerTextB}
                                                onChange={(val: string) => onUpdateItem(item.id, 'answerTextB', val)}
                                                placeholder="Type (ஆ) answer content..."
                                                isAnswerTab={true}
                                            />
                                        </div>
                                    )}

                                    {item.enableDiscourseB && (
                                        <div className="border rounded-xl p-4 bg-indigo-50/30 border-indigo-100 animate-slide-up">
                                            <h4 className="text-[10px] font-black text-indigo-600 uppercase tracking-widest mb-3">Select Discourse (B)</h4>
                                            <select
                                                className="w-full border p-2 rounded-lg text-sm bg-white shadow-sm focus:ring-2 focus:ring-indigo-100 outline-none"
                                                onChange={(e: React.ChangeEvent<HTMLSelectElement>) => {
                                                    const id = e.target.value;
                                                    setSelectedDiscourseIdB(id);
                                                    if (id) applyDiscourse(id, 'answerTextB');
                                                }}
                                                value={selectedDiscourseIdB}
                                            >
                                                <option value="" disabled>-- Choose Discourse --</option>
                                                {availableDiscourses.map((d: Discourse) => (
                                                    <option key={d.id} value={d.id}>{d.name} ({formatMarks(d.marks)} Marks)</option>
                                                ))}
                                            </select>

                                            {/* Discourse Preview B */}
                                            {selectedDiscourseIdB && (
                                                <div className="mt-4 p-5 bg-white border border-purple-100 rounded-xl shadow-[0_4px_20px_-5px_rgba(147,51,234,0.1)] animate-fade-in relative overflow-hidden">
                                                    <div className="absolute top-0 right-0 w-24 h-24 bg-purple-50 rounded-full -mr-12 -mt-12 -z-0 opacity-50"></div>
                                                    
                                                    <div className="relative z-10">
                                                        <div className="flex justify-between items-start mb-3">
                                                            <div>
                                                                <h5 className="font-bold text-purple-900 text-base">{availableDiscourses.find(d => d.id === selectedDiscourseIdB)?.name}</h5>
                                                                <div className="flex flex-wrap gap-2 mt-1">
                                                                    <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-purple-100 text-purple-700 border border-purple-200 uppercase tracking-wide">
                                                                        {availableDiscourses.find(d => d.id === selectedDiscourseIdB)?.cognitiveProcess || 'No CP'}
                                                                    </span>
                                                                    <span className="inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold bg-green-100 text-green-700 border border-green-200 uppercase tracking-wide">
                                                                        {formatMarks(availableDiscourses.find(d => d.id === selectedDiscourseIdB)?.marks || 0)} Marks
                                                                    </span>
                                                                </div>
                                                            </div>
                                                            <span className="text-[9px] bg-slate-100 text-slate-500 px-2 py-1 rounded-full font-black uppercase tracking-tighter">Preview Mode</span>
                                                        </div>

                                                        <div className="bg-slate-50/80 p-3 rounded-lg border border-slate-100 mb-4">
                                                            <p className="text-[11px] leading-relaxed text-slate-600 italic">
                                                                {availableDiscourses.find(d => d.id === selectedDiscourseIdB)?.description}
                                                            </p>
                                                        </div>

                                                        <div className="space-y-1.5">
                                                            <div className="flex items-center gap-2 mb-2">
                                                                <div className="h-[1px] flex-grow bg-purple-100"></div>
                                                                <span className="text-[9px] font-black text-purple-300 uppercase tracking-widest">Rubric Points</span>
                                                                <div className="h-[1px] flex-grow bg-purple-100"></div>
                                                            </div>
                                                            <div className="grid grid-cols-1 gap-1.5">
                                                                {availableDiscourses.find(d => d.id === selectedDiscourseIdB)?.rubrics.map((r: any, i: number) => (
                                                                    <div key={i} className="flex justify-between items-center text-[10px] bg-white p-2.5 rounded-lg border border-purple-50 hover:border-purple-200 hover:shadow-sm transition-all group">
                                                                        <span className="text-slate-700 font-medium">{r.point}</span>
                                                                        <span className="font-bold text-purple-600 bg-purple-50/50 px-2 py-1 rounded border border-purple-100 group-hover:bg-purple-600 group-hover:text-white transition-colors">
                                                                            {formatMarks(r.marks)}
                                                                        </span>
                                                                    </div>
                                                                ))}
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            )}
                                        </div>
                                    )}

                                    {item.enableInputAnswerB && (
                                        <div className="space-y-2 animate-slide-up">
                                            <h4 className="text-[10px] font-black text-green-600 uppercase tracking-widest pl-1">Input Answer (B)</h4>
                                            <StructuredAnswerEditor
                                                value={item.structuredAnswersB || []}
                                                onChange={(val: AnswerMark[]) => {
                                                    onUpdateItem(item.id, 'structuredAnswersB', val as any);
                                                }}
                                            />
                                        </div>
                                    )}

                                    {item.enableFurtherInfoB && (
                                        <div className="space-y-2 animate-slide-up">
                                            <h4 className="text-[10px] font-black text-purple-600 uppercase tracking-widest pl-1">Further Information (B)</h4>
                                            <textarea
                                                rows={2}
                                                className="w-full border-2 border-purple-50 rounded-xl px-4 py-3 text-sm focus:border-purple-300 focus:ring-4 focus:ring-purple-50 outline-none transition-all placeholder:text-gray-300"
                                                placeholder="Enter any additional field information here..."
                                                value={item.furtherInfoB || ''}
                                                onChange={(e) => onUpdateItem(item.id, 'furtherInfoB', e.target.value)}
                                            />
                                        </div>
                                    )}
                                </div>
                            )}
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
};

export default QuestionRow;
